### ISSUE TITLE
Problem about downloading images from JAMSTEC E-library

### ISSUE THREAD

**Issue by Vipermdl** [asanc199/Mask_RCNN-Cleansea#6]
Hi, Dr. Ferrer

It is a good job for marine debris detection. I have a tough question about how to download the image for Cleansea dataset. I noticed you just provide labels for cleansea dataset, but the image need to download in  JAMSTEC E-library website image-by-image, can you provide a available way to download image? Thanks.

**Comment by ajgallego** [comment]
Hi @Vipermdl, 

you can download the dataset from:
https://www.dlsi.ua.es/∼jgallego/datasets/cleansea

Cheers
